---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clustercidr-x-k8s-io-v1-clustercidr
  failurePolicy: Fail
  name: validate.clustercidr.x-k8s.io
  rules:
  - apiGroups:
    - clustercidr.x-k8s.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clustercidrs
  sideEffects: None
