{{- if .Values.installCRDs }}
  {{ range $path, $_ := .Files.Glob "gen/crds/*.yaml" }}
  {{- $crd := $.Files.Get $path | fromYaml -}}
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    {{- $crd.metadata.annotations | toYaml | nindent 4 }}
    helm.sh/resource-policy: keep
  name: {{ $crd.metadata.name }}
spec:
  {{- $crd.spec | toYaml | nindent 2 }}
  {{ end }}
  {{- end}}
